##
## EPITECH PROJECT, 2021
## bistromatic
## File description:
## makefile for computations
##

all:
	make -C add/
	make -c sub/
	make -C mul/
	make -C div/
	make -C mod/

clean:
	make -C add/ clean
	make -C sub/ clean
	make -C mul/ clean
	make -C div/ clean
	make -C mod/ clean
